server:
  port: 9095
spring:
  application:
    name: spring-shardingjdbc
mybatis:
  typeAliasesPackage: com.chengzejun.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/playtest_0
        username: root
        password: 667788dog
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/playtest_1
        username: root
        password: 667788dog

    config:
      sharding:
         defaultDataSourceName: ds0
        # default-database-strategy:
         #   inline:
         #     sharding-column: id
          #    algorithm-expression: ds${id % 2}
         props:
          sql.show: true
         tables:
            t_data_music:
              keyGeneratorColumnName: music_id
              actualDataNodes: ds0.t_data_music_${0..1}
              #database-strategy:
               # inline:
                #  sharding-column: id
                 # algorithm-expression: playtest_$_${id % 2}
              tableStrategy:
                inline:
                  shardingColumn: music_id
                  algorithmExpression: t_data_music_${music_id % 2}
     # t_order_item:
     #   actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      #  databaseStrategy:
       #   inline:
        #    shardingColumn: user_id
        #    algorithmInlineExpression: ds_$_${user_id % 2}
        #tableStrategy:
         # inline:
          #  shardingColumn: order_id
          #  algorithmInlineExpression: t_order_item_${order_id % 2}
  #datasource:
  #  url: jdbc:mysql://127.0.0.1:3306/playtest?useUnicode=true&characterEncoding=utf-8&useSSL=false
  #  username: root
  #  password: 667788dog
  #  driver-class-name: com.mysql.jdbc.Driver
  #  type: com.alibaba.druid.pool.DruidDataSource


