server:
  port: 8084
spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 10.211.55.3
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true
    publisher-returns: true